name: leadgen-pipeline-app
region: ams

ingress:
  rules: []

services:
  - name: leadgen-ui
    github:
      repo: milan-singh121/LeadGenSolution
      branch: main
      deploy_on_push: true
    environment_slug: python
    source_dir: /workspace
    run_command: streamlit run streamlit_app.py
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: STREAMLIT_SERVER_PORT
        value: "8080"
      - key: PYTHONPATH
        value: "/workspace"
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: MONGO_DB_NAME
        value: "LeadGen_Test"
      - key: REDIS_BROKER_URL
        value: ${REDIS_BROKER_URL}
      - key: SNOV_CLIENT_ID
        value: ${SNOV_CLIENT_ID}
      - key: SNOV_CLIENT_SECRET
        value: ${SNOV_CLIENT_SECRET}
      - key: AWS_ACCESS_KEY
        value: ${AWS_ACCESS_KEY}
      - key: AWS_SECRET_KEY
        value: ${AWS_SECRET_KEY}
      - key: AWS_REGION
        value: "us-east-1"
      - key: RAPID_API_KEY
        value: ${RAPID_API_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: REDIS_CA_CERT_B64
        value: ${REDIS_CA_CERT_B64}

  - name: leadgen-worker
    github:
      repo: milan-singh121/LeadGenSolution
      branch: main
      deploy_on_push: true
    environment_slug: python
    source_dir: /
    run_command: celery -A celery_app worker -P gevent --concurrency=10 --loglevel=info
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: PYTHONPATH
        value: "/workspace"
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: MONGO_DB_NAME
        value: "LeadGen_Test"
      - key: REDIS_BROKER_URL
        value: ${REDIS_BROKER_URL}
      - key: SNOV_CLIENT_ID
        value: ${SNOV_CLIENT_ID}
      - key: SNOV_CLIENT_SECRET
        value: ${SNOV_CLIENT_SECRET}
      - key: AWS_ACCESS_KEY
        value: ${AWS_ACCESS_KEY}
      - key: AWS_SECRET_KEY
        value: ${AWS_SECRET_KEY}
      - key: AWS_REGION
        value: "us-east-1"
      - key: RAPID_API_KEY
        value: ${RAPID_API_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: REDIS_CA_CERT_B64
        value: ${REDIS_CA_CERT_B64}

databases:
  - name: redis-broker
    engine: VALKEY
    production: true
    cluster_name: leadgen-broker
