# This is the full and correct specification for your application.
# It defines the UI, the background worker, and the database connection.
name: leadgen-pipeline-app
region: ams # Using your specified region

# Define the services (components) of your application
services:
  - name: leadgen-ui
    # This is your Streamlit web service
    git:
      repo: milan-singh121/LeadGenSolution
      branch: main
    run_command: streamlit run streamlit_app.py
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: STREAMLIT_SERVER_PORT
        value: "8080"
        scope: RUN_TIME
      - key: PYTHONPATH
        value: "/workspace"
        scope: RUN_TIME
      - key: MONGO_URI
        value: "${mongo.MONGO_URI}"
        scope: RUN_TIME
      - key: MONGO_DB_NAME
        value: "LeadGen_Test"
        scope: RUN_TIME
      - key: REDIS_BROKER_URL
        value: "${redis-broker.INTERNAL_URL}"
        scope: RUN_TIME
      - key: SNOV_CLIENT_ID
        value: "${SNOV_CLIENT_ID}"
        type: SECRET
      - key: SNOV_CLIENT_SECRET
        value: "${SNOV_CLIENT_SECRET}"
        type: SECRET
      - key: AWS_ACCESS_KEY
        value: "${AWS_ACCESS_KEY}"
        type: SECRET
      - key: AWS_SECRET_KEY
        value: "${AWS_SECRET_KEY}"
        type: SECRET
      - key: AWS_REGION
        value: "us-east-1"
        scope: RUN_TIME
      - key: RAPID_API_KEY
        value: "${RAPID_API_KEY}"
        type: SECRET
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"
        type: SECRET
      - key: REDIS_CA_CERT_B64
        value: "${REDIS_CA_CERT_B64}"
        type: SECRET

  - name: leadgen-worker
    # This is your Celery worker
    git:
      repo: milan-singh121/LeadGenSolution
      branch: main

    run_command: celery -A celery_app worker -P gevent --concurrency=10 --loglevel=info
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: PYTHONPATH
        value: "/workspace"
        scope: RUN_TIME
      - key: MONGO_URI
        value: "${mongo.MONGO_URI}"
        scope: RUN_TIME
      - key: MONGO_DB_NAME
        value: "LeadGen_Test"
        scope: RUN_TIME
      - key: REDIS_BROKER_URL
        value: "${redis-broker.INTERNAL_URL}"
        scope: RUN_TIME
      - key: SNOV_CLIENT_ID
        value: "${SNOV_CLIENT_ID}"
        type: SECRET
      - key: SNOV_CLIENT_SECRET
        value: "${SNOV_CLIENT_SECRET}"
        type: SECRET
      - key: AWS_ACCESS_KEY
        value: "${AWS_ACCESS_KEY}"
        type: SECRET
      - key: AWS_SECRET_KEY
        value: "${AWS_SECRET_KEY}"
        type: SECRET
      - key: AWS_REGION
        value: "us-east-1"
        scope: RUN_TIME
      - key: RAPID_API_KEY
        value: "${RAPID_API_KEY}"
        type: SECRET
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"
        type: SECRET
      - key: REDIS_CA_CERT_B64
        value: "${REDIS_CA_CERT_B64}"
        type: SECRET

# It links your app to the managed database you created.
databases:
  - name: redis-broker
    engine: VALKEY
    production: true
    # Ensure this name EXACTLY matches the name of your Valkey cluster in the DO dashboard
    cluster_name: "leadgen-broker"

# It defines placeholders for your secrets, which you will fill in the UI.
vars:
  - key: mongo.MONGO_URI
    value: "YOUR_MONGODB_ATLAS_CONNECTION_STRING"
    type: SECRET
  - key: RAPID_API_KEY
    value: ""
    type: SECRET
  - key: SNOV_CLIENT_ID
    value: ""
    type: SECRET
  - key: SNOV_CLIENT_SECRET
    value: ""
    type: SECRET
  - key: AWS_ACCESS_KEY
    value: ""
    type: SECRET
  - key: AWS_SECRET_KEY
    value: ""
    type: SECRET
  - key: OPENAI_API_KEY
    value: ""
    type: SECRET
